// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for FirstRepeatable documents */
interface FirstrepeatableDocumentData {
    /**
     * Title field in *FirstRepeatable*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: firstrepeatable.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * MyImage field in *FirstRepeatable*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: firstrepeatable.myimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    myimage: prismicT.ImageField<never>;
    /**
     * MyDate field in *FirstRepeatable*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: firstrepeatable.mydate
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    mydate: prismicT.DateField;
}
/**
 * FirstRepeatable document from Prismic
 *
 * - **API ID**: `firstrepeatable`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FirstrepeatableDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FirstrepeatableDocumentData>, "firstrepeatable", Lang>;
/** Content for hello documents */
interface HelloDocumentData {
    /**
     * This is how we do it field in *hello*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hello.this_is_how_we_do_it
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    this_is_how_we_do_it: prismicT.KeyTextField;
    /**
     * Slice Zone field in *hello*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: hello.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HelloDocumentDataSlicesSlice>;
}
/**
 * Slice for *hello → Slice Zone*
 *
 */
type HelloDocumentDataSlicesSlice = TrySliceSlice;
/**
 * hello document from Prismic
 *
 * - **API ID**: `hello`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HelloDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HelloDocumentData>, "hello", Lang>;
export type AllDocumentTypes = FirstrepeatableDocument | HelloDocument;
/**
 * Primary content in TrySlice → Primary
 *
 */
interface TrySliceSliceDefaultPrimary {
    /**
     * Hello field in *TrySlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: try_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description2 field in *TrySlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: try_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * imaga field in *TrySlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: try_slice.primary.imaga
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imaga: prismicT.ImageField<never>;
}
/**
 * Item in TrySlice → Items
 *
 */
export interface TrySliceSliceDefaultItem {
    /**
     * DataToday field in *TrySlice → Items*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: try_slice.items[].datatoday
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    datatoday: prismicT.DateField;
}
/**
 * Default variation for TrySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TrySlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TrySliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TrySliceSliceDefaultPrimary>, Simplify<TrySliceSliceDefaultItem>>;
/**
 * Slice variation for *TrySlice*
 *
 */
type TrySliceSliceVariation = TrySliceSliceDefault;
/**
 * TrySlice Shared Slice
 *
 * - **API ID**: `try_slice`
 * - **Description**: `TrySlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TrySliceSlice = prismicT.SharedSlice<"try_slice", TrySliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { FirstrepeatableDocumentData, FirstrepeatableDocument, HelloDocumentData, HelloDocumentDataSlicesSlice, HelloDocument, AllDocumentTypes, TrySliceSliceDefaultPrimary, TrySliceSliceDefaultItem, TrySliceSliceDefault, TrySliceSliceVariation, TrySliceSlice };
    }
}
